### PR TITLE
add keymap help to main buffer

### PR DESCRIPTION
**Pull request by ruefo**
Found it helpful to see the basic commands in the main buffer.

### CODE REVIEW

**Comment by NicolasPetton** [comment]
You can already press `?` in the pass buffer.

**Comment by ruefo** [comment]
Hm. Yes. Don't you?

**Comment by NicolasPetton** [comment]
What I meant was that since `?` will give a you the list of keybindings, showing all keybindings in the pass buffer seems like an overkill to me.

**Comment by ruefo** [comment]
OK, now i get you. Well, i know it's no must-have. However, there are other modes, where this is done in a similar way (e.g. mu4e, magit-popups). As already said, for me (as a relatively new user) it was helpful.  You decide.

**Comment by NicolasPetton** [comment]
Thanks, I gave it a try, and I like it!

**Pull request merged**
